export const ADD_SERVICE = 'ADD_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const SET_EDITABLE_SERVICE_ID = 'SET_EDITABLE_SERVICE_ID';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
